version = 0.1
[default.deploy.parameters]
stack_name = "riassume-appsync-note-api"
resolve_s3 = true
s3_prefix = "riassume-appsync-note-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "APIName=\"Note API\""
image_repositories = []
